
project_id = "pxynugnbikiwbsqdgewx"

[functions.send-contact-email]
verify_jwt = false

[functions.send-custom-email]
verify_jwt = false

[functions.generate-article]
verify_jwt = false

[functions.seed-quiz-data]
verify_jwt = false

